name: coreplugin
version: '${version}'

main: org.coreplugin.Coreplugin
load: STARTUP

commands:
  firestorm:
    description: Control sandstorms
    usage: /firestorm [start [seconds] | stop | status]
