name: coreplugin
version: '${version}'

main: org.coreplugin.CorePlugin
load: STARTUP

commands:
  solarflare:
    description: Control solar flares
    usage: /solarflare [start [seconds] | stop | status]
